################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true
################################################################
# Docker configuration backend
################################################################
providers:
  docker: 
    watch: true
    exposedByDefault: false
    swarmMode: true
################################################################
# Traefik Logging
################################################################
log:
  level: INFO
  # level: DEBUG
