################################################################
# API and dashboard configuration
################################################################
api:
  dashboard: true
  insecure: true

################################################################
# Enable Healthcheck
################################################################
ping: {}

################################################################
# Docker configuration backend
################################################################
providers:
  docker:
    exposedByDefault: false
    
################################################################
# Traefik Logging
################################################################
log:
  level: INFO

################################################################
# Entrypoint
################################################################
entryPoints:
  web:
    address: ":80"
    maxConcurrentStreams: 250
  websecure:
    address: ":443"
    maxConcurrentStreams: 250


################################################################
# Challenge TLS
################################################################
certificatesResolvers:
  myresolver:
    acme:
      email: ckdgus11021@gmail.com
      storage: acme.json
      tlsChallenge: true